apiVersion: apps/v1
kind: Deployment
metadata:
  name: generation
  namespace: vehicle-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generation
  template:
    metadata:
      labels:
        app: generation
    spec:
      containers:
      - name: generation
        image: vehicle-ai/generation:latest
        resources:
          requests:
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            memory: "16Gi"
            nvidia.com/gpu: 1
